### ISSUE TITLE
File read/write... dont work at debuging

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-assembly#126] opened 2020-10-15 06:35 UTC
Unfortunately in debug mode the loading/saving/locking etc. does not work. Here is a small example what just creates a file and wants to write a small text into the file. But the call OPEN always returns with zero.

`ExecBase     = 4
; Exec Library
OpenLibrary  = -552 ;LibName,Version/a1,d0
CloseLibrary = -414 ;LibName,Version/a1,d0
; Dos Library
Open         = -30
Read         = -42
Write        = -48
Close        = -36  
Mode_OldFile = 1005
Mode_NewFile = 1006

;  Start: 
  move.l    ExecBase.w,a6

  ; Open Dos-Library
  lea       (DosName,PC),a1
  moveq     #$00,d0
  jsr       OpenLibrary(a6)
  move.l    d0,DosBase
  
  ; create new file
  move.l    DosBase(PC),a5
  move.l    #Filename,d1
  move.l    #Mode_NewFile,d2
  jsr       Open(a5)
  beq.s     ErrorOpenFile
  move.l    d0,SourceHandle
  
  ; save file
  move.l    SourceHandle,d1
  move.l    #Content,d2
  move.l    #22,d3
  jsr       Write(a5)
  ; close file
  move.l    SourceHandle,d1
  jsr       Close(a5)

ErrorOpenFile:
	; Close Dos Lib
  move.l    DosBase(PC),a1
  cmp       #$00,a1
  beq.s     SkipCloseDosLib
  jsr       CloseLibrary(a6)
SkipCloseDosLib:
  rts

  EVEN
SourceHandle:  dc.l    $0
DosBase:       dc.l    $0
DosName:       dc.b    "dos.library",0
Content:       dc.b    'This is a simple test.'
Filename:      dc.b    'data.dat',0,0`

**Comment by prb28** [comment] 2020-10-15 19:49
Did you try with an absolute path ?
There is some issues with the current directory in debug mode.

**Comment by Real-MJoe** [comment] 2020-10-16 13:20
Sorry my fault and you are right! On my second system the path was wrong. Thats all....grrr

**Comment by prb28** [comment] 2020-10-19 07:15
Duplicate of https://github.com/prb28/vscode-amiga-assembly/issues/112

**Closed by prb28** 2020-10-19 07:15 UTC
Labels: bug
